version: "2.0"
services:
    nginx:
        image: "nginx:alpine"
        ports:
            - "880:80"
            - "8443:443"
        volumes:
            - "./www1/:/www1/"
            - "./nginx/conf.d/:/etc/nginx/conf.d/:ro"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./logs/nginx/:/var/log/nginx/:rw"
        links:
        - fpm:fpm
    fpm:
        build: "./php-fpm"
        ports:
            - "9000"
        volumes:
            - "./www1/:/www1/"
        links:
        - mysql:mysql
        - redis:redis
    mysql:
      image: "mysql:5.7"
      ports:
        - "3301:3306"
      volumes:
        - ./mysql/my.cnf:/etc/mysql/my.cnf:ro
        - ./mysql/data:/var/lib/mysql/:rw
        - ./logs/mysql/:/var/log/mysql/:rw
      environment:
        MYSQL_ROOT_PASSWORD: "123456"

    redis:
      image: "redis:alpine"
      ports:
        - "6301:6379"